# Generated by Django 5.1.5 on 2025-02-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM_A', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abc',
            new_name='ab',
        ),
    ]
